project:
  type: website

website:
  title: "My Data Stories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/davidgarmal/comm3180_S26_Blog
format:
  html:
    theme: solar
    css: styles.css

execute:
  freeze: auto


